"""Visual tests for generators for the validation stage."""
import matplotlib.pyplot as plt
import numpy as np

def run_visual_tests(generator, n_samples: int = 100_000) -> None:
    """Runs visual tests for the given generator."""   
    if n_samples < 2:
        raise ValueError("n_samples must be >= 2 for scatter plot analysis")

    # Matplotlib figure init
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle(f"Analiza wizualna generatora: {generator.name}", fontsize=16)

    # Get samples from generator
    floats = generator.random_floats(n_samples)
    
    # 1. Histogram (is the generated sample uniform?)
    axs[0, 0].hist(floats, bins=100, density=True, color='skyblue', edgecolor='black', alpha=0.7)
    axs[0, 0].axhline(y=1, color='r', linestyle='--')
    axs[0, 0].set_title("Histogram wartości (oczekiwany rozkład płaski)")
    axs[0, 0].set_xlim(0, 1)

    # 2. Scatter plot 2D - spectral analysis (x_n vs x_{n+1})
    # Use up to 2000 adjacent pairs, but support smaller samples as well.
    pair_count = min(len(floats) - 1, 2000)
    x_n = floats[:pair_count]
    x_n1 = floats[1 : pair_count + 1]
    axs[0, 1].scatter(x_n, x_n1, s=2, color='darkblue', alpha=0.5)
    axs[0, 1].set_title("Scatter plot 2D (x_n vs x_{n+1})")
    axs[0, 1].set_xlim(0, 1)
    axs[0, 1].set_ylim(0, 1)

    # 3. Noise image (image of 256x256 greyscale pixels from generated bytes)
    img_size = 256
    raw_bytes = generator.random_bytes(img_size * img_size)
    # Convert bytes to 2D numpy array (0-255)
    img_array = np.frombuffer(raw_bytes, dtype=np.uint8).reshape((img_size, img_size))
    im = axs[1, 0].imshow(img_array, cmap='gray', interpolation='none')
    axs[1, 0].set_title(f"Obraz szumu ({img_size}x{img_size})")
    fig.colorbar(im, ax=axs[1, 0], fraction=0.046, pad=0.04)

    # 4. Random walk 1D
    bits = generator.random_bits(10_000)
    steps = np.array([1 if b == 1 else -1 for b in bits])
    walk = np.cumsum(steps)
    axs[1, 1].plot(walk, color='purple', linewidth=1)
    axs[1, 1].axhline(y=0, color='black', linestyle='--')
    axs[1, 1].set_title("Błądzenie losowe 1D (10 000 kroków)")

    plt.tight_layout()
    plt.show()
